import { Users, Briefcase, Zap, TrendingUp, Search, BarChart3, Target, AlertCircle } from 'lucide-react';

export const servicesData = [
  {
    id: 1,
    title: "تیم‌سازی",
    subtitle: "ساخت تیم حرفه‌ای برای کسب‌وکار شما",
    icon: Users,
    iconBg: "bg-emerald-300/30",
    bgHover: "bg-emerald-500",
    iconColor: "white",
  },
  {
    id: 2,
    title: "مشاوره کسب‌وکار",
    subtitle: "راهنمایی حرفه‌ای برای تبدیل ایده به کسب‌وکار",
    icon: Briefcase,
    iconBg: "bg-blue-300/30",
    bgHover: "bg-blue-500",
    iconColor: "white",
  },
  {
    id: 3,
    title: "راه‌اندازی استارتاپ",
    subtitle: "از صفر تا صد راه‌اندازی کسب‌وکار دیجیتال",
    icon: Zap,
    iconBg: "bg-purple-300/30",
    bgHover: "bg-purple-500",
    iconColor: "white",
  },
  {
    id: 4,
    title: "رشد و توسعه",
    subtitle: "استراتژی‌های رشد و بهینه‌سازی کسب‌وکار",
    icon: TrendingUp,
    iconBg: "bg-orange-300/30",
    bgHover: "bg-orange-500",
    iconColor: "white",
  },
  {
    id: 5,
    title: "SEO و بهینه‌سازی وب‌سایت",
    subtitle: "بهبود رتبه‌بندی وب‌سایت‌ها در موتورهای جستجو",
    icon: Search,
    iconBg: "bg-red-300/30",
    bgHover: "bg-red-500",
    iconColor: "white",
  },
  {
    id: 6,
    title: "تحلیل داده‌ها",
    subtitle: "استفاده از داده‌های کلان برای تصمیم‌گیری‌های بهتر",
    icon: BarChart3,
    iconBg: "bg-pink-300/30",
    bgHover: "bg-pink-500",
    iconColor: "white",
  },
  {
    id: 7,
    title: "دیجیتال مارکتینگ",
    subtitle: "استراتژی‌های بازاریابی دیجیتال پیشرفته",
    icon: Target,
    iconBg: "bg-indigo-300/30",
    bgHover: "bg-indigo-500",
    iconColor: "white",
  },
  {
    id: 8,
    title: "مدیریت ریسک",
    subtitle: "شناسایی و مدیریت ریسک‌های کسب‌وکار",
    icon: AlertCircle,
    iconBg: "bg-cyan-300/30",
    bgHover: "bg-cyan-500",
    iconColor: "white",
  },
];
